"""Inspect the schema generated by the installed Codex App Server."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any

from appserver_protocol import REQUIRED_NOTIFICATION_METHODS, REQUIRED_REQUEST_METHODS


@dataclass(frozen=True)
class CapabilityReport:
    compatible: bool
    request_methods: frozenset[str]
    notification_methods: frozenset[str]
    missing_requests: frozenset[str]
    missing_notifications: frozenset[str]
    errors: tuple[str, ...]

    def public(self) -> dict[str, Any]:
        return {
            "compatible": self.compatible,
            "requestMethodCount": len(self.request_methods),
            "notificationMethodCount": len(self.notification_methods),
            "missingRequests": sorted(self.missing_requests),
            "missingNotifications": sorted(self.missing_notifications),
            "errors": list(self.errors),
        }


def _enum_strings(value: Any) -> set[str]:
    result: set[str] = set()
    if isinstance(value, dict):
        enum = value.get("enum")
        if isinstance(enum, list):
            result.update(
                item
                for item in enum
                if isinstance(item, str) and ("/" in item or item == "initialize")
            )
        for child in value.values():
            result.update(_enum_strings(child))
    elif isinstance(value, list):
        for child in value:
            result.update(_enum_strings(child))
    return result


def _methods(path: Path) -> tuple[frozenset[str], str | None]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except OSError:
        return frozenset(), f"missing schema: {path.name}"
    except json.JSONDecodeError:
        return frozenset(), f"invalid schema: {path.name}"
    return frozenset(_enum_strings(value)), None


def inspect_schema_directory(path: Path) -> CapabilityReport:
    requests, request_error = _methods(path / "ClientRequest.json")
    notifications, notification_error = _methods(path / "ServerNotification.json")
    errors = tuple(error for error in (request_error, notification_error) if error)
    missing_requests = REQUIRED_REQUEST_METHODS - requests
    missing_notifications = REQUIRED_NOTIFICATION_METHODS - notifications
    return CapabilityReport(
        compatible=not errors and not missing_requests and not missing_notifications,
        request_methods=requests,
        notification_methods=notifications,
        missing_requests=missing_requests,
        missing_notifications=missing_notifications,
        errors=errors,
    )
