version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:20'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      javascript-dependencies:
        patterns: ['*']
    commit-message:
      prefix: deps

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:30'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      python-dependencies:
        patterns: ['*']
    commit-message:
      prefix: deps

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:40'
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    groups:
      workflow-actions:
        patterns: ['*']
    commit-message:
      prefix: deps
