import { build } from 'esbuild';
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const toolDir = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(toolDir, '..', '..');
const outputDir = path.join(
  repositoryRoot,
  'apps/owner/local-tmux-owner/static/vendor/markdown-ast',
);
const highlightOutputDir = path.join(outputDir, 'highlight');

await mkdir(outputDir, { recursive: true });
// This directory is generated exclusively by this build. Removing it first
// prevents obsolete content-hashed language chunks from leaking into releases.
await rm(highlightOutputDir, { recursive: true, force: true });
const result = await build({
  absWorkingDir: toolDir,
  entryPoints: [path.join(toolDir, 'src/index.js')],
  outfile: path.join(outputDir, 'markdown-ast.min.js'),
  bundle: true,
  format: 'iife',
  globalName: 'FaryoMarkdownAst',
  legalComments: 'eof',
  metafile: true,
  minify: true,
  sourcemap: false,
  target: ['es2020'],
  banner: {
    js: '/*! Faryo AST Markdown engine; bundled dependencies and DeepSeek-derived extensions are documented in THIRD_PARTY_NOTICES.md. */',
  },
});
const highlightResult = await build({
  absWorkingDir: toolDir,
  entryPoints: [path.join(toolDir, 'src/highlight.js')],
  outdir: outputDir,
  bundle: true,
  chunkNames: 'highlight/chunks/[name]-[hash]',
  entryNames: 'highlight/[name]',
  format: 'esm',
  legalComments: 'eof',
  metafile: true,
  minify: true,
  sourcemap: false,
  splitting: true,
  target: ['es2020'],
  banner: {
    js: '/*! Faryo on-demand Shiki highlighter; see ../THIRD_PARTY_NOTICES.md. */',
  },
});

const highlightFiles = Object.entries(highlightResult.metafile.outputs)
  .map(([output, metadata]) => {
    const absolute = path.isAbsolute(output) ? output : path.resolve(toolDir, output);
    const relative = path.relative(outputDir, absolute).split(path.sep).join('/');
    if (!relative.startsWith('highlight/') || relative.includes('../')) {
      throw new Error('Highlighter output escaped its generated directory: ' + output);
    }
    return { path: relative, bytes: metadata.bytes };
  })
  .sort((left, right) => left.path.localeCompare(right.path));
if (!highlightFiles.some((item) => item.path === 'highlight/highlight.js')) {
  throw new Error('Highlighter entry was not generated');
}
await writeFile(
  path.join(highlightOutputDir, 'manifest.json'),
  JSON.stringify({
    schemaVersion: 1,
    entry: 'highlight/highlight.js',
    files: highlightFiles,
  }, null, 2) + '\n',
  'utf8',
);

const packageRoots = new Map();
for (const input of [
  ...Object.keys(result.metafile.inputs),
  ...Object.keys(highlightResult.metafile.inputs),
]) {
  const absolute = path.resolve(toolDir, input);
  const parts = absolute.split(path.sep);
  const marker = parts.lastIndexOf('node_modules');
  if (marker < 0 || marker + 1 >= parts.length) continue;
  const end = parts[marker + 1].startsWith('@') ? marker + 3 : marker + 2;
  const root = parts.slice(0, end).join(path.sep);
  packageRoots.set(root, root);
}

const licenseGroups = new Map();
for (const root of [...packageRoots.values()].sort()) {
  const metadata = JSON.parse(await readFile(path.join(root, 'package.json'), 'utf8'));
  const files = await readdir(root);
  const licenseFile = files
    .filter((name) => /^licen[cs]e(?:\..*)?$/iu.test(name))
    .sort((left, right) => left.length - right.length || left.localeCompare(right))[0];
  if (!licenseFile) {
    throw new Error('Bundled package has no license file: ' + metadata.name);
  }
  const license = (await readFile(path.join(root, licenseFile), 'utf8')).trim();
  const key = license.replace(/\r\n/gu, '\n');
  if (!licenseGroups.has(key)) licenseGroups.set(key, []);
  licenseGroups.get(key).push(metadata.name + '@' + metadata.version);
}

const deepSeekLicense = (
  await readFile(path.join(toolDir, 'licenses/deepseek-harness-mit.txt'), 'utf8')
).trim();
const sections = [
  'Faryo AST Markdown engine third-party licenses',
  '',
  'Generated by tools/markdown-engine/build.mjs from the exact package-lock.',
  '',
  'DeepSeek Harness-derived mathCompatibility and cjkFriendlyStrong',
  'Source commit: 47f943859bef60e4160492346772ded9b24f765a',
  '',
  deepSeekLicense,
];
for (const [license, packages] of licenseGroups) {
  sections.push('', 'Bundled packages: ' + packages.sort().join(', '), '', license);
}
await writeFile(
  path.join(outputDir, 'THIRD_PARTY_LICENSES.txt'),
  sections.join('\n') + '\n',
  'utf8',
);
